#### Warm-up exercise to recall iterations

In [1]:
names = ["NGC 5128", "TXS 0506+056", "NGC 1068", "GB6 J1040+0617", "TXS 2226-184"]
distances = [3.7, 1.75e3, 14.4, 1.51e4, 107.1]  # Mpc
luminosities = [1e40, 3e46, 4.9e38, 6.2e45, 5.5e41] # erg/s

gal_cat = list(zip(names, distances, luminosities))

for name, dist, lum in gal_cat:
    print(f"{name:15s} D={dist:.2e} Mpc, L={lum:.2e} erg/s")

NGC 5128        D=3.70e+00 Mpc, L=1.00e+40 erg/s
TXS 0506+056    D=1.75e+03 Mpc, L=3.00e+46 erg/s
NGC 1068        D=1.44e+01 Mpc, L=4.90e+38 erg/s
GB6 J1040+0617  D=1.51e+04 Mpc, L=6.20e+45 erg/s
TXS 2226-184    D=1.07e+02 Mpc, L=5.50e+41 erg/s


# Intro to numpy
### 2/12/2022

In [5]:
import numpy as np

## Creating 1D arrays

In [450]:
arr1 = np.arange(15)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
arr2 = np.arange(3,25,2)
print(arr2)

[ 3  5  7  9 11 13 15 17 19 21 23]


In [26]:
np.array([])

array([], dtype=float64)

In [21]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [24]:
np.ones(10) # Same as np.full(10,1.)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.zeros(10)# Same as np.full(10, 0.)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(0) # Same as np.array([])

array([], dtype=float64)

In [36]:
# Check the size of an array
print(arr1.size)

15


In [ ]:
np.linspace()

In [ ]:
np.logspace()

In [297]:
randarr = np.random.randint(30,51,16)
print(randarr)

[39 39 39 43 37 47 41 33 47 31 46 50 30 50 49 42]


In [452]:
arr4 = np.concatenate([arr1,arr1])
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8
  9 10 11 12 13 14]


## Indexing in 1D

In [298]:
print(randarr[4])

37


In [299]:
print(randarr[2:6])

[39 43 37 47]


In [300]:
print(randarr[:3])

[39 39 39]


In [301]:
print(randarr[3:])

[43 37 47 41 33 47 31 46 50 30 50 49 42]


In [302]:
print(randarr[:])

[39 39 39 43 37 47 41 33 47 31 46 50 30 50 49 42]


In [303]:
print(randarr[:-1])

[39 39 39 43 37 47 41 33 47 31 46 50 30 50 49]


## Simple array operations

In [304]:
arr1 = np.linspace(10,100,10)
print(arr1)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [117]:
print(arr1 * 0.01)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [121]:
sqarr = arr1 ** 2
print(sqarr)
newarr = sqarr + arr1
print(newarr)

[  100.   400.   900.  1600.  2500.  3600.  4900.  6400.  8100. 10000.]
[  110.   420.   930.  1640.  2550.  3660.  4970.  6480.  8190. 10100.]


In [126]:
print(np.exp(1), np.log10(100), np.pi)

2.718281828459045 2.0 3.141592653589793


In [122]:
# This is fine:
print(np.arange(10) + np.arange(10))
# But this will give an error:
# print(np.arange(10) + np.arange(12))


[ 0  2  4  6  8 10 12 14 16 18]


## Comparison operates on an element-by-element basis!

In [305]:
islarge = randarr > 40
print(randarr)
print(islarge)

[39 39 39 43 37 47 41 33 47 31 46 50 30 50 49 42]
[False False False  True False  True  True False  True False  True  True
 False  True  True  True]


In [ ]:
## Aggreagte functions

In [306]:
# Sum
arr3 = np.arange(10)
np.sum(arr3)

45

In [59]:
# Product
arr5 = np.linspace(3.,5.,3)
print(arr5)
arr6 = np.prod(arr5)
print(arr6)

[3. 4. 5.]
60.0


In [65]:
# Exercise: calculate average of x**2 between -1 and 5 using linspace, sum, and size
np.mean(np.linspace(-1,5,1))

-1.0

In [74]:
np.mean(randarr)

61.55555555555556

In [72]:
np.min(randarr), np.max(randarr)

(33, 98)

##### Side note: inside math operations, `True` has value 1 and `False` 0

In [225]:
print(f"{True + False=}")
print(f"{True * False=}")
print(f"{True + True=}")
print(f"{True * np.pi=}")
print(f"{False * np.pi=}")

True + False=1
True * False=0
True + True=2
True * np.pi=3.141592653589793
False * np.pi=0.0


This means we can use `np.sum` to count how many elements fulfill our criterion:

In [230]:
print(randarr)
print(randarr > 40)
count = np.sum(randarr > 40)
print(f"{count} numbers above 40.")

[98 58 66 87 35 38 33 90 49]
[ True  True  True  True False False False  True  True]
6 numbers above 40.


In [75]:
np.any(randarr<40)

True

In [78]:
np.any(randarr<30)

False

In [76]:
np.all(randarr>40)

False

In [142]:
np.all(randarr>30)

True

In [250]:
# Exercise: prime numbers

def isprime(n):
    for i in range(2,n):
        if not n % i:
            return False
    return True

def isprime_numpy(n):
    return np.all(n % np.arange(2,n))


In [287]:
%%time
isprime(90911)

CPU times: user 8.31 ms, sys: 173 µs, total: 8.49 ms
Wall time: 8.61 ms


True

In [288]:
%%time
isprime_numpy(90911)

CPU times: user 2.99 ms, sys: 892 µs, total: 3.88 ms
Wall time: 2.48 ms


True

In [205]:
def countprimes(n):
    count = 0
    for i in range(2,n+1):
        if isprime(i):
            count += 1
    return count

countprimes(1000)

def countprimes_numpy(n):
    return np.sum(n % np.arange(2,n))

## Shapes

In [416]:
print(randarr.shape)
print(randarr.size)

(16,)
16


In [311]:
rand2d = randarr.reshape(4,4)
print(rand2d)
print(rand2d.shape)

[[39 39 39 43]
 [37 47 41 33]
 [47 31 46 50]
 [30 50 49 42]]
(4, 4)


In [417]:
ran2d = np.arange(100).reshape(10,10)
print(ran2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [400]:
rand2d_tr = np.transpose(ran2d)
print(rand2d_tr)

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]]


In [401]:
print(ran2d.shape, ran2d.size)

(10, 10) 100


In numpy, indexing doesn't have to be done dimension by dimension, like with lists:

In [381]:
ran2d[2][1]

21

Instead, we can access elements directly with multiple indices (faster and more readable)

In [383]:
ran2d[2,1]

21

### With this syntax I can also access slices of my arrays along any axis, as well as "chunks":

In [413]:
print(ran2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [414]:
hslice = ran2d[1,:] # Same as ran2d[1] (same as with a list)
print(hslice)

[10 11 12 13 14 15 16 17 18 19]


In [408]:
vslice = ran2d[:,1] # Not so straightforward with lists!
print(vslice)

[ 1 11 21 31 41 51 61 71 81 91]


### Exercise: create a 3D array from np.arange(100) with any shape you like

In [438]:
ran3d = ran2d.reshape(2,5,10)
print(ran3d)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


### Think pair share: what parts of my 3D matrix do these lines of code access?

In [429]:
ran3d[0,:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [430]:
ran3d[:,0,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [431]:
ran3d[:,:,0]

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

## Operations along different axes

In [613]:
testmat = np.arange(6).reshape(3,2)
print(testmat)

[[0 1]
 [2 3]
 [4 5]]


In [622]:
np.sum(testmat) # default is axis=None, which simply sums all the elements

15

In [623]:
print(np.sum(testmat, axis=0))
print(np.sum(testmat, axis=1))

[6 9]
[1 5 9]


## Concatenating arrays in multiple dimensions

By default, concatenation happens along the first dimension (i.e. axis 0):

In [558]:
arr1 = np.arange(15).reshape(5,3)
arr2 = arr1 * 10
print(arr1)
print(arr2)
print(arr1.shape, arr2.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]
 [120 130 140]]
(5, 3) (5, 3)


In [559]:
conc1 = np.concatenate([arr1, arr2]) # same as passing axis=0
print(conc1)
print(conc1.shape)

[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]
 [  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]
 [120 130 140]]
(10, 3)


To concatenate arrays along other axes, you an specify the axis number, which tells you the dimension along which you're concatenating the arrays:

In [560]:
conc2 = np.concatenate([arr1, arr2], axis=1)
print(conc2)

[[  0   1   2   0  10  20]
 [  3   4   5  30  40  50]
 [  6   7   8  60  70  80]
 [  9  10  11  90 100 110]
 [ 12  13  14 120 130 140]]


#### Think-pair-share: which of these 2 operations leads to an error?

In [569]:
arr15 = np.arange(15).reshape(5,3)
arr10 = np.arange(10).reshape(5,2)
# This:
# np.concatenate((arr15, arr10), axis=0)
# or this:
# np.concatenate((arr15, arr10), axis=1)

### To multiply a matrix with a vector, the vector has to have the same size as the last dimension of your matrix!

In [507]:
mat1 = np.arange(20).reshape(2,10)
vec1 = np.arange(10)
vec2 = np.arange(2)

print(mat1)
print(vec1)
print(vec2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[0 1 2 3 4 5 6 7 8 9]
[0 1]


In [523]:
mat1 * vec1

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  0,  11,  24,  39,  56,  75,  96, 119, 144, 171]])

In [525]:
# This won't work: 
#mat1 * vec2

# So instead, I can transpose my 
# matrix to give it the right shape: 
mat1.T * vec2

array([[ 0, 10],
       [ 0, 11],
       [ 0, 12],
       [ 0, 13],
       [ 0, 14],
       [ 0, 15],
       [ 0, 16],
       [ 0, 17],
       [ 0, 18],
       [ 0, 19]])

The same goes for other operations like addition, division, and so on.